import { query, mutation } from "./_generated/server";
import { v } from "convex/values";
import { assertAdmin, requireAdminOrPortal } from "./lib/auth";

export const list=query({args:{adminKey:v.optional(v.string()),portalToken:v.optional(v.string()),clientId:v.optional(v.id("clients")),projectId:v.optional(v.id("projects")),status:v.optional(v.string())},handler:async(ctx,args)=>{const auth=await requireAdminOrPortal(ctx,args.adminKey,args.portalToken);const clientId=auth.isAdmin?args.clientId:auth.clientId;if(clientId){const rows=await ctx.db.query("tickets").withIndex("by_client",q=>q.eq("client_id",clientId)).collect();return(args.status?rows.filter(t=>t.status===args.status):rows).sort((a,b)=>b._creationTime-a._creationTime);}if(args.projectId)return await ctx.db.query("tickets").withIndex("by_project",q=>q.eq("project_id",args.projectId!)).collect();if(args.status){const rows=await ctx.db.query("tickets").withIndex("by_status",q=>q.eq("status",args.status as any)).collect();return rows.sort((a,b)=>b._creationTime-a._creationTime);}return(await ctx.db.query("tickets").collect()).sort((a,b)=>b._creationTime-a._creationTime);}});
export const get=query({args:{adminKey:v.optional(v.string()),portalToken:v.optional(v.string()),id:v.id("tickets")},handler:async(ctx,args)=>{const auth=await requireAdminOrPortal(ctx,args.adminKey,args.portalToken);const ticket=await ctx.db.get(args.id);if(!ticket)return null;if(!auth.isAdmin&&ticket.client_id!==auth.clientId)throw new Error("Unauthorized");return ticket;}});
export const create=mutation({args:{adminKey:v.optional(v.string()),portalToken:v.optional(v.string()),client_id:v.optional(v.id("clients")),project_id:v.optional(v.id("projects")),subject:v.string(),category:v.union(v.literal("bug"),v.literal("feature_request"),v.literal("support"),v.literal("billing"),v.literal("general")),priority:v.optional(v.union(v.literal("low"),v.literal("medium"),v.literal("high"),v.literal("urgent"))),message:v.string(),sender_name:v.string()},handler:async(ctx,args)=>{const auth=await requireAdminOrPortal(ctx,args.adminKey,args.portalToken);const clientId=auth.isAdmin?args.client_id:auth.clientId;if(!clientId)throw new Error("Client required");if(args.project_id){const project=await ctx.db.get(args.project_id);if(!project||project.client_id!==clientId)throw new Error("Unauthorized project");}const id=await ctx.db.insert("tickets",{client_id:clientId,project_id:args.project_id,subject:args.subject,category:args.category,priority:args.priority||"medium",status:"open"});await ctx.db.insert("ticket_messages",{ticket_id:id,sender_type:auth.isAdmin?"admin":"client",sender_name:args.sender_name,message:args.message});return id;}});
export const updateStatus=mutation({args:{adminKey:v.string(),id:v.id("tickets"),status:v.union(v.literal("open"),v.literal("in_progress"),v.literal("waiting_on_client"),v.literal("resolved"),v.literal("closed"))},handler:async(ctx,args)=>{assertAdmin(args.adminKey);const updates:any={status:args.status};if(args.status==="resolved"||args.status==="closed")updates.resolved_at=Date.now();await ctx.db.patch(args.id,updates);}});
export const updatePriority=mutation({args:{adminKey:v.string(),id:v.id("tickets"),priority:v.union(v.literal("low"),v.literal("medium"),v.literal("high"),v.literal("urgent"))},handler:async(ctx,args)=>{assertAdmin(args.adminKey);await ctx.db.patch(args.id,{priority:args.priority});}});
export const getMessages=query({args:{adminKey:v.optional(v.string()),portalToken:v.optional(v.string()),ticketId:v.id("tickets")},handler:async(ctx,args)=>{const auth=await requireAdminOrPortal(ctx,args.adminKey,args.portalToken);const ticket=await ctx.db.get(args.ticketId);if(!ticket||(!auth.isAdmin&&ticket.client_id!==auth.clientId))throw new Error("Unauthorized");return await ctx.db.query("ticket_messages").withIndex("by_ticket",q=>q.eq("ticket_id",args.ticketId)).collect();}});
export const addMessage=mutation({args:{adminKey:v.optional(v.string()),portalToken:v.optional(v.string()),ticket_id:v.id("tickets"),sender_type:v.union(v.literal("client"),v.literal("admin")),sender_name:v.string(),message:v.string()},handler:async(ctx,args)=>{const auth=await requireAdminOrPortal(ctx,args.adminKey,args.portalToken);const ticket=await ctx.db.get(args.ticket_id);if(!ticket||(!auth.isAdmin&&ticket.client_id!==auth.clientId))throw new Error("Unauthorized");const senderType=auth.isAdmin?args.sender_type:"client";await ctx.db.insert("ticket_messages",{ticket_id:args.ticket_id,sender_type:senderType,sender_name:args.sender_name,message:args.message});if(senderType==="admin"&&ticket.status==="open")await ctx.db.patch(args.ticket_id,{status:"in_progress"});else if(senderType==="client"&&ticket.status==="waiting_on_client")await ctx.db.patch(args.ticket_id,{status:"in_progress"});}});
export const remove=mutation({args:{adminKey:v.string(),id:v.id("tickets")},handler:async(ctx,args)=>{assertAdmin(args.adminKey);const messages=await ctx.db.query("ticket_messages").withIndex("by_ticket",q=>q.eq("ticket_id",args.id)).collect();for(const msg of messages)await ctx.db.delete(msg._id);await ctx.db.delete(args.id);}});
export const counts=query({args:{adminKey:v.string()},handler:async(ctx,args)=>{assertAdmin(args.adminKey);const all=await ctx.db.query("tickets").collect();return{total:all.length,open:all.filter(t=>t.status==="open").length,in_progress:all.filter(t=>t.status==="in_progress").length,waiting:all.filter(t=>t.status==="waiting_on_client").length,resolved:all.filter(t=>t.status==="resolved"||t.status==="closed").length};}});
